services:
  ketai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ket-ai
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - ./config.json:/app/config.json:rw
      - ./system.txt:/app/system.txt:ro
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
